---
title: "Software I've written"
mathjax: true
output:
  blogdown::html_page:
    toc: true
---

```{r, label = setup, include = FALSE, cache = FALSE}
library(knitr)
opts_chunk$set(
              #  fig.path   = 'figure/'
                cache.path = 'cache/'
               , cache      = FALSE
               , dev        = c("svg", "tikz", "pdf", "png")[1]
               , fig.align  = 'center'
              # , fig.show   = 'asis'
              # , fig.width  = 6
              # , fig.height = 6
              # , out.width  = '0.9\\linewidth'
               , par        = TRUE
               , echo       = TRUE
               , results    = 'markup'
               , warning    = FALSE
               , message    = FALSE
               , comment    = NA
               )
options(
          replace.assign = TRUE
        , width          = 80
        , knitr.kable.NA = ''
        )

knit_hooks$set(par = function(before, options, envir){
if (before && options$fig.show!='none')
 par(mar=c(4, 4, 0.1, 0.1), cex.lab = 0.95, cex.axis =0.9, mgp = c(2, 0.7, 0), tcl = -0.3)
}, crop = hook_pdfcrop)

# Suppressing Error Messages in knitr
muffleError <- function(x,options) {}
knit_hooks$set(error=muffleError)
```

&nbsp;

This page provides links to R & LaTeX packages I have (co)authored. The most recent versions of most packages are on [github](https://github.com/myaseen208/). Most R packages are also on [CRAN](http://cran.rstudio.com).

&nbsp;

# R Packages/Software

## bayesammi

> [**bayesammi**](https://cran.r-project.org/web/packages/bayesammi/index.html) :  *Bayesian Estimation of the Additive Main Effects and Multiplicative Interaction Model* [[Website](https://myaseen208.github.io/bayesammi)]

&nbsp;

## baystability
> [**baystability**](https://cran.r-project.org/web/packages/baystability/index.html) :  *Bayesian Stability Analysis of Genotype by Environment Interaction (GEI)* [[Website](https://myaseen208.github.io/baystability)]

&nbsp;

## DiallelAnalysisR
> [**DiallelAnalysisR**](https://cran.r-project.org/web/packages/DiallelAnalysisR/index.html) :  *Diallel Analysis with R* [[Website](https://myaseen208.github.io/DiallelAnalysisR)]

&nbsp;

## eda4treeR
> [**eda4treeR**](https://cran.r-project.org/web/packages/eda4treeR/index.html) :  *Experimental Design and Analysis for Tree Improvement* [[Website](https://myaseen208.github.io/eda4treeR)]

&nbsp;

## gvcR
> [**gvcR**](https://cran.r-project.org/web/packages/gvcR/index.html) :  *Genotypic Variance Components* [[Website](https://myaseen208.github.io/gvcR)]

&nbsp;

## PakPC2017
> [**PakPC2017**](https://cran.r-project.org/web/packages/PakPC2017/index.html) :  *Pakistan Population Census 2017* [[Website](https://myaseen208.github.io/PakPC2017)]

&nbsp;

## PakPMICS2014Ch
> [**PakPMICS2014Ch**](https://cran.r-project.org/web/packages/PakPMICS2014Ch/index.html) :  *Multiple Indicator Cluster Survey (MICS) 2014 Child Questionnaire Data for Punjab, Pakistan* [[Website](https://myaseen208.github.io/PakPMICS2014Ch)]

&nbsp;

## PakPMICS2014HH
> [**PakPMICS2014HH**](https://cran.r-project.org/web/packages/PakPMICS2014HH/index.html) :  *Multiple Indicator Cluster Survey (MICS) 2014 Household Questionnaire Data for Punjab, Pakistan* [[Website](https://myaseen208.github.io/PakPMICS2014HH)]

&nbsp;

## PakPMICS2014HL
> [**PakPMICS2014HL**](https://cran.r-project.org/web/packages/PakPMICS2014HL/index.html) :  *Multiple Indicator Cluster Survey (MICS) 2014 Household Listing Questionnaire Data for Punjab, Pakistan* [[Website](https://myaseen208.github.io/PakPMICS2014HL)]

&nbsp;

## PakPMICS2014Wm
> [**PakPMICS2014Wm**](https://cran.r-project.org/web/packages/PakPMICS2014Wm/index.html) :  *Multiple Indicator Cluster Survey (MICS) 2014 Women Questionnaire Data for Punjab, Pakistan* [[Website](https://myaseen208.github.io/PakPMICS2014Wm)]

&nbsp;

## ppcSpatial
> [**ppcSpatial**](https://cran.r-project.org/web/packages/ppcSpatial/index.html) :  *Spatial Analysis of Pakistan Population Census* [[Website](https://myaseen208.github.io/ppcSpatial)]

&nbsp;

## PSLM2015
> [**PSLM2015**](https://cran.r-project.org/web/packages/PSLM2015/index.html) :  *Pakistan Social and Living Standards Measurement Survey 2014-15* [[Website](https://myaseen208.github.io/PSLM2015)]

&nbsp;

## stability
> [**stability**](https://cran.r-project.org/web/packages/stability/index.html) :  *Stability Analysis of Genotype by Environment Interaction (GEI)* [[Website](https://myaseen208.github.io/stability)]

&nbsp;

## StroupGLMM
> [**StroupGLMM**](https://cran.r-project.org/web/packages/StroupGLMM/index.html) :  *R Codes and Datasets for Generalized Linear Mixed Models: Modern Concepts, Methods and Applications by Walter W. Stroup* [[github](https://myaseen208.github.io/StroupGLMM)]

&nbsp;

## VetResearchLMM
> [**VetResearchLMM**](https://cran.r-project.org/web/packages/VetResearchLMM/index.html) :  *Linear Mixed Models: An Introduction with Applications in Veterinary Research* [[Website](https://myaseen208.github.io/VetResearchLMM)]


&nbsp;

# LaTeX Packages/Software

## UAFSynopsis
> [**UAFSynopsis**](https://github.com/myaseen208/UAFSynopsis) :  *LaTeX class for the Synopsis of the University of Agriculture, Faisalabad-Pakistan* [[github](https://github.com/myaseen208/UAFSynopsis)]

&nbsp;

## UAFThesis
> [**UAFThesis**](https://github.com/myaseen208/UAFThesis) :  *LaTeX class for the Thesis of the University of Agriculture, Faisalabad-Pakistan* [[github](https://github.com/myaseen208/UAFThesis)]


&nbsp;

## PakJAS
> [**PakJAS**](https://github.com/myaseen208/PakJAS) :  *LaTeX class for Pakistan Journal of Agricultural Sciences* [[github](https://github.com/myaseen208/PakJAS)]
